### ISSUE TITLE
Error with AR_RandomColors

### ISSUE THREAD

**Issue by robertvoy** [aturtur/cinema4d-scripts#25]
When I control + click the script I get the gradient dialogue and then when I confirm it I get the error below. 

`AttributeError: 'c4d.Gradient' object has no attribute 'GetColor'
Traceback (most recent call last):
  File "C:\Users\Robert\AppData\Roaming\Maxon\Maxon Cinema 4D 2024_A5DBFF93\library\scripts\cinema4d-scripts\AR_Scripts_1.76\Object Manager\AR_RandomColors.py", line 94, in Command
    ColorizeWithGradient(grad) # Colorize objects
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Robert\AppData\Roaming\Maxon\Maxon Cinema 4D 2024_A5DBFF93\library\scripts\cinema4d-scripts\AR_Scripts_1.76\Object Manager\AR_RandomColors.py", line 111, in ColorizeWithGradient
    gradient.InitRender(irs)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'c4d.Gradient' object has no attribute 'InitRender'`

**Comment by robertvoy** [comment]
Updated to latest version and it solved the issue.
